// Auto-generated by scripts/generate-clients-data.mjs
// Do not edit manually.

export interface Client {
  name: string;
  url?: string;
  logo: string;
  big?: boolean;
  scale?: number;
}

export const clients: Client[] = [
  {
    "name": "1922",
    "url": "https://1922.co.id",
    "logo": "/images/client/1922.png"
  },
  {
    "name": "3 Second",
    "logo": "/images/client/3-second.png",
    "big": true
  },
  {
    "name": "Acer",
    "url": "https://www.acer.com",
    "logo": "/images/client/acer.svg"
  },
  {
    "name": "Adhi",
    "url": "https://adhi.co.id",
    "logo": "/images/client/adhi.png"
  },
  {
    "name": "Advos",
    "logo": "/images/client/advos.png"
  },
  {
    "name": "Amarta Wisesa",
    "url": "https://amartawisesa.com",
    "logo": "/images/client/amarta-wisesa.png"
  },
  {
    "name": "Antangin",
    "url": "https://antangin.com",
    "logo": "/images/client/antangin.png",
    "big": true
  },
  {
    "name": "Baiturrokhman",
    "url": "https://baiturrokhmantour.com",
    "logo": "/images/client/baiturrokhman.png"
  },
  {
    "name": "Bang Bana",
    "url": "https://bangbana.com",
    "logo": "/images/client/bang-bana.png"
  },
  {
    "name": "Bank Jatim",
    "url": "https://bankjatim.co.id",
    "logo": "/images/client/bank-jatim.png"
  },
  {
    "name": "Bank Mandiri",
    "url": "https://bankmandiri.co.id",
    "logo": "/images/client/bank-mandiri.svg"
  },
  {
    "name": "Bank Sidoarjo",
    "logo": "/images/client/bank-sidoarjo.png"
  },
  {
    "name": "Begawan Premium Student Apartment",
    "logo": "/images/client/begawan-premium-student-apartment.png"
  },
  {
    "name": "Berrys",
    "logo": "/images/client/berrys.png"
  },
  {
    "name": "Bestdough",
    "url": "https://bestdougid.com",
    "logo": "/images/client/bestdough.png"
  },
  {
    "name": "Bluder Kapas",
    "logo": "/images/client/bluder-kapas.png"
  },
  {
    "name": "Bni",
    "url": "https://bni.co.id",
    "logo": "/images/client/bni.png",
    "big": true
  },
  {
    "name": "Boop",
    "url": "https://www.boopin.com",
    "logo": "/images/client/boop.png"
  },
  {
    "name": "Bpr Artha Kanjuruhan",
    "logo": "/images/client/bpr-artha-kanjuruhan.png",
    "big": true
  },
  {
    "name": "Bri",
    "url": "https://bri.co.id",
    "logo": "/images/client/bri.webp",
    "big": true
  },
  {
    "name": "Bumiputera",
    "url": "https://bumiputera.com",
    "logo": "/images/client/bumiputera.png"
  },
  {
    "name": "Calon Istri",
    "logo": "/images/client/calon-istri.png"
  },
  {
    "name": "Catoel",
    "logo": "/images/client/catoel.png"
  },
  {
    "name": "Chatten",
    "logo": "/images/client/chatten.png"
  },
  {
    "name": "Coca Cola",
    "url": "https://www.coca-cola.co.id",
    "logo": "/images/client/coca-cola.svg",
    "big": true
  },
  {
    "name": "Consult",
    "logo": "/images/client/consult.png"
  },
  {
    "name": "Cross",
    "logo": "/images/client/cross.png"
  },
  {
    "name": "Daihatsu",
    "url": "https://astra-daihatsu.id",
    "logo": "/images/client/daihatsu.webp",
    "big": true
  },
  {
    "name": "Dailbana",
    "logo": "/images/client/dailbana.png",
    "scale": 1.5
  },
  {
    "name": "Dana",
    "url": "https://www.dana.id",
    "logo": "/images/client/dana.svg"
  },
  {
    "name": "Dhika Universe",
    "logo": "/images/client/dhika-universe.png"
  },
  {
    "name": "Dinar Weddover",
    "logo": "/images/client/dinar-weddover.png"
  },
  {
    "name": "Diplomat",
    "logo": "/images/client/diplomat.png"
  },
  {
    "name": "Djarum",
    "url": "https://www.djarum.com",
    "logo": "/images/client/djarum.png",
    "big": true
  },
  {
    "name": "Djoglo",
    "logo": "/images/client/djoglo.png"
  },
  {
    "name": "Dr Dhelay",
    "logo": "/images/client/dr-dhelay.png"
  },
  {
    "name": "Electronic City",
    "logo": "/images/client/electronic-city.png"
  },
  {
    "name": "Ertekn",
    "logo": "/images/client/ertekn.png"
  },
  {
    "name": "Etawa Plus",
    "logo": "/images/client/etawa-plus.png"
  },
  {
    "name": "Fertisoil",
    "logo": "/images/client/fertisoil.png",
    "big": true
  },
  {
    "name": "Fifgroup",
    "url": "https://www.fifgroup.co.id",
    "logo": "/images/client/fifgroup.png"
  },
  {
    "name": "First",
    "logo": "/images/client/first.png"
  },
  {
    "name": "Fpg Insurance",
    "logo": "/images/client/fpg-insurance.png"
  },
  {
    "name": "Gellate",
    "logo": "/images/client/gellate.png"
  },
  {
    "name": "Gita",
    "logo": "/images/client/gita.png"
  },
  {
    "name": "Hamur Kurasi",
    "logo": "/images/client/hamur-kurasi.png"
  },
  {
    "name": "Hanoman",
    "logo": "/images/client/hanoman.png"
  },
  {
    "name": "Helwa",
    "logo": "/images/client/helwa.png"
  },
  {
    "name": "Hodai",
    "logo": "/images/client/hodai.png"
  },
  {
    "name": "Holcim",
    "url": "https://www.holcim.co.id",
    "logo": "/images/client/holcim.png",
    "big": true
  },
  {
    "name": "Honda",
    "url": "https://www.astra-honda.com",
    "logo": "/images/client/honda.webp",
    "big": true
  },
  {
    "name": "Hotel Santika",
    "url": "https://www.santika.com",
    "logo": "/images/client/hotel-santika.png"
  },
  {
    "name": "In Lite",
    "logo": "/images/client/in-lite.png"
  },
  {
    "name": "Indana",
    "logo": "/images/client/indana.png",
    "big": true
  },
  {
    "name": "Indofood",
    "url": "https://www.indofood.com",
    "logo": "/images/client/indofood.png",
    "big": true
  },
  {
    "name": "Indomaret",
    "url": "https://indomaret.co.id",
    "logo": "/images/client/indomaret.webp"
  },
  {
    "name": "Indosat",
    "url": "https://ioh.co.id",
    "logo": "/images/client/indosat.svg",
    "big": true
  },
  {
    "name": "Inspiring City",
    "logo": "/images/client/inspiring-city.png"
  },
  {
    "name": "Jamkrindo",
    "url": "https://jamkrindo.co.id",
    "logo": "/images/client/jamkrindo.png"
  },
  {
    "name": "Japfa",
    "url": "https://www.japfacomfeed.co.id",
    "logo": "/images/client/japfa.png"
  },
  {
    "name": "Jatim Park",
    "url": "https://www.jatimpark.com",
    "logo": "/images/client/jatim-park.png"
  },
  {
    "name": "Jco",
    "url": "https://www.jcodonuts.com",
    "logo": "/images/client/jco.png"
  },
  {
    "name": "Jiwasraya",
    "url": "https://www.jiwasraya.co.id",
    "logo": "/images/client/jiwasraya.png"
  },
  {
    "name": "Kabupaten Malang",
    "logo": "/images/client/kabupaten-malang.png"
  },
  {
    "name": "Kampung Kramat",
    "logo": "/images/client/kampung-kramat.png"
  },
  {
    "name": "Kek",
    "logo": "/images/client/kek.png"
  },
  {
    "name": "Kementerian Pertanian",
    "url": "https://www.pertanian.go.id",
    "logo": "/images/client/kementerian-pertanian.png"
  },
  {
    "name": "Kitabeli",
    "logo": "/images/client/kitabeli.png",
    "big": true
  },
  {
    "name": "Konas",
    "logo": "/images/client/konas.png"
  },
  {
    "name": "Konimex",
    "url": "https://konimex.com",
    "logo": "/images/client/konimex.png",
    "big": true
  },
  {
    "name": "Kota Karismatik Madiun",
    "logo": "/images/client/kota-karismatik-madiun.png"
  },
  {
    "name": "Kota Madiun",
    "logo": "/images/client/kota-madiun.png"
  },
  {
    "name": "Kpu",
    "url": "https://www.kpu.go.id",
    "logo": "/images/client/kpu.png"
  },
  {
    "name": "La Tobas Cigar Premium",
    "logo": "/images/client/la-tobas-cigar-premium.png"
  },
  {
    "name": "Lakoni",
    "logo": "/images/client/lakoni.png",
    "big": true
  },
  {
    "name": "Malang Kucecwara",
    "logo": "/images/client/malang-kucecwara.png"
  },
  {
    "name": "Mcc",
    "logo": "/images/client/mcc.png"
  },
  {
    "name": "Mccpg",
    "logo": "/images/client/mccpg.png"
  },
  {
    "name": "Mie Gacoan",
    "url": "https://miegacoan.com",
    "logo": "/images/client/mie-gacoan.webp",
    "big": true
  },
  {
    "name": "Mie Jogja",
    "logo": "/images/client/mie-jogja.png"
  },
  {
    "name": "Mom Sarasa",
    "logo": "/images/client/mom-sarasa.png"
  },
  {
    "name": "Ms Glow",
    "logo": "/images/client/ms-glow.png",
    "big": true
  },
  {
    "name": "Naavagreen",
    "logo": "/images/client/naavagreen.png"
  },
  {
    "name": "Nastle",
    "logo": "/images/client/nastle.png",
    "big": true
  },
  {
    "name": "Nelongso",
    "logo": "/images/client/nelongso.png"
  },
  {
    "name": "Nobu",
    "logo": "/images/client/nobu.png"
  },
  {
    "name": "Nokia",
    "url": "https://www.nokia.com",
    "logo": "/images/client/nokia.svg"
  },
  {
    "name": "Odigiro",
    "logo": "/images/client/odigiro.png"
  },
  {
    "name": "Ollino Garden",
    "logo": "/images/client/ollino-garden.png"
  },
  {
    "name": "Oppo",
    "url": "https://www.oppo.com/id",
    "logo": "/images/client/oppo.webp"
  },
  {
    "name": "Ot",
    "logo": "/images/client/ot.png"
  },
  {
    "name": "Pegadaian",
    "url": "https://www.pegadaian.co.id",
    "logo": "/images/client/pegadaian.webp"
  },
  {
    "name": "Perbamida",
    "logo": "/images/client/perbamida.png"
  },
  {
    "name": "Pertamina",
    "url": "https://www.pertamina.com",
    "logo": "/images/client/pertamina.svg",
    "big": true
  },
  {
    "name": "Pia Cap Mangkok",
    "logo": "/images/client/pia-cap-mangkok.png"
  },
  {
    "name": "Pln",
    "url": "https://www.pln.co.id",
    "logo": "/images/client/pln.png",
    "big": true
  },
  {
    "name": "Pt Bpr Bank Tulungagung",
    "logo": "/images/client/pt-bpr-bank-tulungagung.png"
  },
  {
    "name": "Pt Central Mega Kencana",
    "logo": "/images/client/pt-central-mega-kencana.png"
  },
  {
    "name": "Pt Econusa Kualiva Abadi",
    "logo": "/images/client/pt-econusa-kualiva-abadi.png"
  },
  {
    "name": "Pt Indo Lakto",
    "logo": "/images/client/pt-indo-lakto.png",
    "big": true
  },
  {
    "name": "Pt Inti Dragon",
    "logo": "/images/client/pt-inti-dragon.png"
  },
  {
    "name": "Raja Gula",
    "logo": "/images/client/raja-gula.png"
  },
  {
    "name": "Realme",
    "url": "https://www.realme.com/id",
    "logo": "/images/client/realme.svg",
    "big": true
  },
  {
    "name": "Robot",
    "logo": "/images/client/robot.png"
  },
  {
    "name": "Rohani",
    "logo": "/images/client/rohani.png"
  },
  {
    "name": "Rsi Unisma Malang",
    "logo": "/images/client/rsi-unisma-malang.png",
    "big": true
  },
  {
    "name": "Rssa",
    "logo": "/images/client/rssa.png"
  },
  {
    "name": "Rubylicious",
    "logo": "/images/client/rubylicious.png",
    "big": true
  },
  {
    "name": "Ruvodo",
    "logo": "/images/client/ruvodo.png",
    "big": true
  },
  {
    "name": "Sampoerna",
    "url": "https://www.sampoerna.com",
    "logo": "/images/client/sampoerna.svg",
    "big": true
  },
  {
    "name": "Satu Titik",
    "logo": "/images/client/satu-titik.png"
  },
  {
    "name": "Sidu",
    "logo": "/images/client/sidu.png"
  },
  {
    "name": "Smartfren",
    "url": "https://www.smartfren.com",
    "logo": "/images/client/smartfren.png",
    "big": true
  },
  {
    "name": "Smoore",
    "logo": "/images/client/smoore.png"
  },
  {
    "name": "Stamford Indonesia Fc",
    "logo": "/images/client/stamford-indonesia-fc.png"
  },
  {
    "name": "Teh Gelas",
    "logo": "/images/client/teh-gelas.png"
  },
  {
    "name": "Tekopi",
    "logo": "/images/client/tekopi.png"
  },
  {
    "name": "Telkomsel",
    "url": "https://www.telkomsel.com",
    "logo": "/images/client/telkomsel.webp",
    "big": true
  },
  {
    "name": "The Alana",
    "logo": "/images/client/the-alana.png",
    "big": true
  },
  {
    "name": "Tiga Roda",
    "logo": "/images/client/tiga-roda.png"
  },
  {
    "name": "Tripa",
    "logo": "/images/client/tripa.png"
  },
  {
    "name": "Universitas Brawijaya",
    "url": "https://ub.ac.id",
    "logo": "/images/client/universitas-brawijaya.webp",
    "big": true
  },
  {
    "name": "Uwg",
    "logo": "/images/client/uwg.png"
  },
  {
    "name": "Vivan",
    "logo": "/images/client/vivan.png"
  },
  {
    "name": "Wika",
    "url": "https://www.wika.co.id",
    "logo": "/images/client/wika.png"
  },
  {
    "name": "Wismari",
    "logo": "/images/client/wismari.png",
    "big": true
  },
  {
    "name": "Xl Axiata",
    "url": "https://www.xlaxiata.co.id",
    "logo": "/images/client/xl-axiata.png",
    "big": true
  },
  {
    "name": "Yamaha",
    "url": "https://www.yamaha-motor.co.id",
    "logo": "/images/client/yamaha.png",
    "big": true
  },
  {
    "name": "You Wang You",
    "logo": "/images/client/you-wang-you.png"
  }
];
